### ISSUE TITLE
Add base filters

### ISSUE THREAD

**Issue by Yago** [endemiq/endemiq#4]
Related user story: #3 

**Todo**
Steps to achieve the task:
- [ ] Add filter modal
- [ ] Add “type” filter
- [ ] Add “labels” filter

**Expected result**
Basic, but fully working filter system
